public class Acc_Con_Case_Record 
{
	public Static Void ListMethod()
    {
        List <Account> lstacc = New List<Account>();
        Account acc = New Account();
        acc.Name = 'Ketaki';
        acc.Rating = 'Hot';
        acc.AnnualRevenue = 4525000;
        acc.Industry ='Banking';
        
        LstAcc.add(acc);
        if(! lstacc.isEmpty())
        {
            
        }
        
        
    }
}